
DROP TABLE IF EXISTS `GP_STOCK_DEAL`;
CREATE TABLE `GP_STOCK_DEAL` (
  `SYMBOL` varchar(32) NOT NULL COMMENT '机构标识',
  `SNAME` varchar(128) NOT NULL COMMENT '机构名称',
  `PRICE` int(11) NOT NULL COMMENT '收盘价格',
  `AMPLITUDE` int(11) NOT NULL COMMENT '涨跌幅度',
  `TDATE` varchar(32) NOT NULL COMMENT '交易日期',
  `IN_TIME` datetime DEFAULT NULL COMMENT '入库时间',
  KEY `IDX_STOCK_DATE` (`TDATE`) USING BTREE,
  KEY `IDX_STOCK` (`SYMBOL`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='查询用的机构信息';
