INSERT INTO `T_M_ROLES` (`ROLE_ID`, `ROLE_NAME`, `IS_VALID`) VALUES (1, '系统管理员', '1');
INSERT INTO `T_M_ROLES` (`ROLE_ID`, `ROLE_NAME`, `IS_VALID`) VALUES (2, '普通用户', '1');
INSERT INTO `T_M_ROLES` (`ROLE_ID`, `ROLE_NAME`, `IS_VALID`) VALUES (3, '管理员', '0');
