INSERT INTO `T_METRIC_WEB` (`WEB_METRIC_ID`, `WEB_METRIC_CODE`, `WEB_METRIC_TITLE`, `IS_VALID`) VALUES (1, 'hostStatusDetail', '主机状态明细', '1');
INSERT INTO `T_METRIC_WEB` (`WEB_METRIC_ID`, `WEB_METRIC_CODE`, `WEB_METRIC_TITLE`, `IS_VALID`) VALUES (2, 'serviceStatusDetail', '服务状态明细', '1');
INSERT INTO `T_METRIC_WEB` (`WEB_METRIC_ID`, `WEB_METRIC_CODE`, `WEB_METRIC_TITLE`, `IS_VALID`) VALUES (3, 'hostStatus', '主机状态', '1');
INSERT INTO `T_METRIC_WEB` (`WEB_METRIC_ID`, `WEB_METRIC_CODE`, `WEB_METRIC_TITLE`, `IS_VALID`) VALUES (4, 'hostServiceStatus', '主机服务状态', '1');
INSERT INTO `T_METRIC_WEB` (`WEB_METRIC_ID`, `WEB_METRIC_CODE`, `WEB_METRIC_TITLE`, `IS_VALID`) VALUES (5, 'hostInfo', '主机信息', '1');
INSERT INTO `T_METRIC_WEB` (`WEB_METRIC_ID`, `WEB_METRIC_CODE`, `WEB_METRIC_TITLE`, `IS_VALID`) VALUES (6, 'metricReport', '指标报表', '1');
