INSERT INTO `T_METRIC_WEB_SUB_DETAIL` (`SUB_WEB_METRIC_ID`, `METRIC_TITLE`, `METRIC_SELECTOR`, `VALUE_TYPE`, `ORDER_NUM`, `IS_VALID`) VALUES (1, 'data', 'data', NULL, 1, '1');
INSERT INTO `T_METRIC_WEB_SUB_DETAIL` (`SUB_WEB_METRIC_ID`, `METRIC_TITLE`, `METRIC_SELECTOR`, `VALUE_TYPE`, `ORDER_NUM`, `IS_VALID`) VALUES (2, 'data', 'data', NULL, 1, '1');
INSERT INTO `T_METRIC_WEB_SUB_DETAIL` (`SUB_WEB_METRIC_ID`, `METRIC_TITLE`, `METRIC_SELECTOR`, `VALUE_TYPE`, `ORDER_NUM`, `IS_VALID`) VALUES (3, 'data', 'data', NULL, 1, '1');
INSERT INTO `T_METRIC_WEB_SUB_DETAIL` (`SUB_WEB_METRIC_ID`, `METRIC_TITLE`, `METRIC_SELECTOR`, `VALUE_TYPE`, `ORDER_NUM`, `IS_VALID`) VALUES (4, 'data', 'data', NULL, 1, '1');
INSERT INTO `T_METRIC_WEB_SUB_DETAIL` (`SUB_WEB_METRIC_ID`, `METRIC_TITLE`, `METRIC_SELECTOR`, `VALUE_TYPE`, `ORDER_NUM`, `IS_VALID`) VALUES (5, 'data', 'data', NULL, 1, '1');
