INSERT INTO `T_REL_WEB_METRIC_SUB` (`WEB_METRIC_ID`, `SUB_WEB_METRIC_ID`) VALUES (1, 1);
INSERT INTO `T_REL_WEB_METRIC_SUB` (`WEB_METRIC_ID`, `SUB_WEB_METRIC_ID`) VALUES (2, 2);
INSERT INTO `T_REL_WEB_METRIC_SUB` (`WEB_METRIC_ID`, `SUB_WEB_METRIC_ID`) VALUES (3, 1);
INSERT INTO `T_REL_WEB_METRIC_SUB` (`WEB_METRIC_ID`, `SUB_WEB_METRIC_ID`) VALUES (3, 3);
INSERT INTO `T_REL_WEB_METRIC_SUB` (`WEB_METRIC_ID`, `SUB_WEB_METRIC_ID`) VALUES (4, 2);
INSERT INTO `T_REL_WEB_METRIC_SUB` (`WEB_METRIC_ID`, `SUB_WEB_METRIC_ID`) VALUES (5, 3);
INSERT INTO `T_REL_WEB_METRIC_SUB` (`WEB_METRIC_ID`, `SUB_WEB_METRIC_ID`) VALUES (5, 4);
INSERT INTO `T_REL_WEB_METRIC_SUB` (`WEB_METRIC_ID`, `SUB_WEB_METRIC_ID`) VALUES (6, 5);
