INSERT INTO `T_REL_METRIC_TEMPLATE` (`WEB_METRIC_ID`, `TEMPLATE_ID`, `IS_VALID`) VALUES (1, 1, '1');
INSERT INTO `T_REL_METRIC_TEMPLATE` (`WEB_METRIC_ID`, `TEMPLATE_ID`, `IS_VALID`) VALUES (2, 2, '1');
INSERT INTO `T_REL_METRIC_TEMPLATE` (`WEB_METRIC_ID`, `TEMPLATE_ID`, `IS_VALID`) VALUES (3, 3, '1');
INSERT INTO `T_REL_METRIC_TEMPLATE` (`WEB_METRIC_ID`, `TEMPLATE_ID`, `IS_VALID`) VALUES (4, 4, '1');
INSERT INTO `T_REL_METRIC_TEMPLATE` (`WEB_METRIC_ID`, `TEMPLATE_ID`, `IS_VALID`) VALUES (5, 5, '1');
INSERT INTO `T_REL_METRIC_TEMPLATE` (`WEB_METRIC_ID`, `TEMPLATE_ID`, `IS_VALID`) VALUES (6, 6, '1');
