INSERT INTO `T_U_CONFIG` (`USER_ID`, `CONFIG_NAME`, `CONFIG_VALUE`) VALUES (-1, 'API_URL_PREFIX', 'http://192.168.6.121:8471');
INSERT INTO `T_U_CONFIG` (`USER_ID`, `CONFIG_NAME`, `CONFIG_VALUE`) VALUES (-1, 'DEFAULT_CLUSTER', 'AISC');
