CREATE TABLE `T_LOG_LOGIN` (
  `LOG_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '流水号',
  `USER_ID` int(11) NOT NULL COMMENT '用户编号',
  `KEY` varchar(128) NOT NULL COMMENT '用户密钥',
  `LOGIN_TIME` datetime NOT NULL COMMENT '登陆时间',
  `LOGOUT_TIME` datetime DEFAULT NULL COMMENT '退出登陆时间',
  `CLIENT_IP` varchar(64) DEFAULT NULL COMMENT '客户端地址',
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;