CREATE TABLE `T_METRIC_WEB_SUB_DETAIL` (
  `DETAIL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SUB_WEB_METRIC_ID` int(11) NOT NULL COMMENT 'WEB指标子编号',
  `METRIC_TITLE` varchar(128) NOT NULL COMMENT '指标说明',
  `METRIC_SELECTOR` varchar(256) NOT NULL COMMENT '指标值选择器',
  `VALUE_TYPE` varchar(128) DEFAULT NULL COMMENT '取值属性。空表示取正文；非空则取对应的属性值',
  `ORDER_NUM` int(11) NOT NULL DEFAULT '1' COMMENT '显示顺序',
  `IS_VALID` char(1) NOT NULL DEFAULT '1' COMMENT '是否有效。可选值：0 无效；1有效。默认1',
  PRIMARY KEY (`DETAIL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COMMENT='WEB指标子配置明细表';

