
CREATE TABLE `GP_AGENCY` (
  `AGENCY_SYMBOL` varchar(32) NOT NULL COMMENT '机构标识',
  `SNAME` varchar(128) NOT NULL COMMENT '机构名称',
  `PATH` varchar(1024) DEFAULT NULL COMMENT '访问路径',
  `IN_TIME` datetime DEFAULT NULL COMMENT '入库时间',
  PRIMARY KEY (`AGENCY_SYMBOL`),
  UNIQUE KEY `UNI_SNAME` (`SNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='机构信息';