CREATE TABLE `GP_AGENCY_Q` (
  `AGENCY_SYMBOL` varchar(32) DEFAULT NULL COMMENT '机构标识',
  `SNAME` varchar(128) NOT NULL COMMENT '机构名称',
  PRIMARY KEY (`SNAME`),
  KEY `IDX_Q_AGENCY_SYMBOL` (`AGENCY_SYMBOL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='查询用的机构信息';